<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to My Website</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </nav>
    <main>
        <h1>Welcome to My Modern Website</h1>
        <p>This is a clean and responsive homepage built with HTML, CSS, and JavaScript.</p>
        <button onclick="showMessage()">Click Me</button>
        <p id="message"></p>
    </main>
    <script src="script.js"></script>
</body>
</html>
